version: '3.1'
services:
  app-pm2:
      container_name: app-pm2
      #构建容器
      build: ./backend
      #直接从git拉去
      # build: git@github.com:su37josephxia/docker_ci.git#:backend
      # 需要链接本地代码时
      # volumes:
      #   - ./backend:/usr/src/app
      ports:
        - "3009:3009"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always 
    ports:
      - 8081:8081
  nginx:
    restart: always
    image: nginx
    ports: # 8091:80 
      - 8091:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./frontend/dist:/var/www/html/
      - ./static/:/static/


# 使用 docker-compose up -d --force-recreate --build
# docker-compose up
# docker-compose down